[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }

log = "0.4"
simple_logger = "4.0.0"
structopt = "0.3.26"
tokio = { version = "1.21.2", features = ["full"] }
tokio-tungstenite = "0.17.2"
futures-util = "0.3.25"
serde_json = "1.0"
